export default [
  {
    id: 1,
    firstName: 'Yana',
    secondName: 'Shkiruk',
    age: '12',
    artName: 'Ornamented murals',
    firstNameUkr: 'Яна',
    secondNameUkr: 'Шкірук',
    artNameUkr: 'Орнаментовані мурали',
  },
  {
    id: 2,
    firstName: 'Olga',
    secondName: 'Oliynuk',
    age: '15',
    artName: 'My Ukraine is picturesque and hospitable',
    firstNameUkr: 'Ольга',
    secondNameUkr: 'Олійник',
    artNameUkr: 'Мальовнича і гостинна моя Україна',
  },
  {
    id: 3,
    firstName: 'Maria',
    secondName: 'Shchigorets',
    age: '12',
    artName: 'The sun of victory',
    firstNameUkr: 'Марія',
    secondNameUkr: 'Щигорець',
    artNameUkr: 'Сонце перемоги',
  },
  {
    id: 4,
    firstName: 'Oleksandra',
    secondName: 'Vitvitska',
    age: '17',
    artName: 'Native country',
    firstNameUkr: 'Олександра',
    secondNameUkr: 'Вітвіцька',
    artNameUkr: 'Рідна країна',
  },

  {
    id: 5,
    firstName: 'Sofiya',
    secondName: 'Lukomskaya',
    age: '8',
    artName: 'Ukraine of hope',
    firstNameUkr: 'Софія',
    secondNameUkr: 'Лукомська',
    artNameUkr: 'Україна надії',
  },

  {
    id: 6,
    firstName: 'Yuliya',
    secondName: 'Melnikovich',
    age: '17',
    artName: 'I and Ukraine',
    firstNameUkr: 'Юлія',
    secondNameUkr: 'Мельникович ',
    artNameUkr: 'Я і Україна',
  },
  {
    id: 7,
    firstName: 'Bohdan',
    secondName: 'Chubik',
    age: '9',
    artName: 'Free country',
    firstNameUkr: 'Богдан',
    secondNameUkr: 'Чубик',
    artNameUkr: 'Вільна країна',
  },
  {
    id: 8,
    firstName: 'Valentyna',
    secondName: 'Lukishchenko',
    age: '11',
    artName: 'Picturesque Ukraine',
    firstNameUkr: 'Валентина',
    secondNameUkr: 'Лукіщенко',
    artNameUkr: 'Мальовнича Україна',
  },
  {
    id: 9,
    firstName: 'Vira',
    secondName: 'Harchenko',
    age: '14',
    artName: 'Oh, my Ukraine!',
    firstNameUkr: 'Віра',
    secondNameUkr: 'Харченко',
    artNameUkr: 'Україно моя',
  },
  {
    id: 10,
    firstName: 'Sofia',
    secondName: 'Zaykova',
    age: '17',
    artName: 'My Krasnograd region after the war',
    firstNameUkr: 'Софія',
    secondNameUkr: 'Зайкова',
    artNameUkr: 'Моя красноградщина після війни',
  },
  {
    id: 11,
    firstName: 'Vladyslav',
    secondName: 'Carpa',
    age: '8',
    artName: 'I believe in the Armed Forces',
    firstNameUkr: 'Владислав',
    secondNameUkr: 'Карпа',
    artNameUkr: 'Вірю в ЗСУ',
  },
  {
    id: 12,
    firstName: 'Mykyta',
    secondName: 'Korobka',
    age: '11',
    artName: 'We will endure',
    firstNameUkr: 'Микита',
    secondNameUkr: 'Коробка',
    artNameUkr: 'Ми вистоїмо',
  },
  {
    id: 13,
    firstName: 'Oleksiy',
    secondName: 'Masanov',
    age: '15',
    artName: 'The enemy will not pass',
    firstNameUkr: 'Олексій',
    secondNameUkr: 'Масанов',
    artNameUkr: 'Врог не пройде',
  },
  {
    id: 14,
    firstName: 'Maxim',
    secondName: 'Kozlovsky',
    age: '12',
    artName: 'Defender of Ukraine',
    firstNameUkr: 'Максим',
    secondNameUkr: 'Козловський',
    artNameUkr: 'Захисник України',
  },
  {
    id: 15,
    firstName: 'Orusya',
    secondName: 'Kyzmenko',
    age: '11',
    artName: 'War is a horror',
    firstNameUkr: 'Орися',
    secondNameUkr: 'Кузьменко',
    artNameUkr: 'Війна – це жахіття',
  },
  {
    id: 16,
    firstName: 'Marietta',
    secondName: 'Brutian',
    age: '15',
    artName: 'Heroes of today',
    firstNameUkr: 'Марієтта',
    secondNameUkr: 'Брутян',
    artNameUkr: 'Герої сьогодення',
  },
  {
    id: 17,
    firstName: 'Kyrul',
    secondName: 'Krasnousov',
    age: '14',
    artName: 'Angels who save lives',
    firstNameUkr: 'Кіріл',
    secondNameUkr: 'Красноусов',
    artNameUkr: 'Янголи, які рятують життя',
  },
  {
    id: 18,
    firstName: 'Iryna',
    secondName: 'Kuschova',
    age: '17',
    artName: 'Ukraine in my eyes',
    firstNameUkr: 'Ірина',
    secondNameUkr: 'Кущова',
    artNameUkr: 'Україна моїми очима',
  },
  {
    id: 19,
    firstName: 'Anastasia',
    secondName: 'Puhach',
    age: '10',
    artName: 'When darkness comes, he will always arrive',
    firstNameUkr: 'Анастасія',
    secondNameUkr: 'Пугач',
    artNameUkr: 'Коли прийде пітьма завжди прилетить він',
  },
  {
    id: 20,
    firstName: 'Nadiya',
    secondName: 'Parchenko',
    age: '14',
    artName: 'Peaceful spring capital',
    firstNameUkr: 'Надія',
    secondNameUkr: 'Парченко',
    artNameUkr: 'Мирна весняна столиця',
  },
  {
    id: 21,
    firstName: 'Oleksandr',
    secondName: 'Semisal',
    age: '13',
    artName: 'Kharkiv of the future',
    firstNameUkr: 'Олександр',
    secondNameUkr: 'Семисал',
    artNameUkr: 'Харків майбутнього',
  },
  {
    id: 22,
    firstName: 'Olga',
    secondName: 'Zolotukhina',
    age: '15',
    artName: 'Looking to the future',
    firstNameUkr: 'Ольга',
    secondNameUkr: 'Золотухіна',
    artNameUkr: 'Погляд в майбутнє',
  },
  {
    id: 23,
    firstName: 'Vira',
    secondName: 'Moskalenko',
    age: '11',
    artName: 'Happy animals in a free country',
    firstNameUkr: 'Віра',
    secondNameUkr: 'Москаленко',
    artNameUkr: 'Щасливі тварини у вільній країні',
  },
  {
    id: 24,
    firstName: 'Viktoria',
    secondName: 'Radychak',
    age: '8',
    artName: 'Ukraine of the future',
    firstNameUkr: 'Вікторія',
    secondNameUkr: 'Радищак',
    artNameUkr: 'Україна Майбутнього',
  },
  {
    id: 25,
    firstName: 'Kseniya',
    secondName: 'Chekulayeva',
    age: '11',
    artName: 'Prosperous Ukraine',
    firstNameUkr: 'Ксенія',
    secondNameUkr: 'Чекулаєва',
    artNameUkr: 'Квітуча Україна',
  },
  {
    id: 26,
    firstName: 'Maria',
    secondName: 'Ivannikova',
    age: '14',
    artName: 'Rebuilt Ukrainian street',
    firstNameUkr: 'Марія',
    secondNameUkr: 'Іваннікова',
    artNameUkr: 'Відбудована українська вулиця',
  },
  {
    id: 27,
    firstName: 'Mark',
    secondName: 'Semenyuk',
    age: '8',
    artName: 'Ukraine of the future',
    firstNameUkr: 'Марк',
    secondNameUkr: 'Семенюк',
    artNameUkr: 'Україна майбутнього',
  },
  {
    id: 28,
    firstName: 'Anastasia',
    secondName: 'Myronenko',
    age: '15',
    artName: 'Forward to a peaceful country',
    firstNameUkr: 'Анастасія',
    secondNameUkr: 'Мироненко',
    artNameUkr: 'Вперед в мирну Україну',
  },
  {
    id: 29,
    firstName: 'Margarita',
    secondName: 'Baidyuk',
    age: '15',
    artName: 'Sightseeing of the native city',
    firstNameUkr: 'Маргарита',
    secondNameUkr: 'Байдюк',
    artNameUkr: 'Памʼятка рідного міста',
  },
];
